

INSERT INTO `LOAINHANVIEN` (`MALOAINV`, `TENLOAINV`) VALUES
(1, 'ADMIN'),
(2, 'KHACHHANG'),
(3, 'KHACHBUON'),
(4, 'NGUOIMUA'),
(5, 'SHIPPER');
INSERT INTO `KHACHHANG` (`MAKH`, `TENKH`, `SDT`, `DIACHI`, `MK`, `MALOAINV`, `EMAIL`) VALUES
(1, 'ADMIN', '1234', 'XUÂN TRƯỜNG - NAM ĐỊNH', 'NOPASS', 1, 'TRACHPRO'),
(2, 'KHACHHANG', '222', 'XÓM 2 - XUÂN DỤC - XUÂN NINH', 'NOPASS', 2, 'VÃI LÚA'),
(3, 'KHACHBUON', '333', 'XÓM 2 - XUÂN DỤC - XUÂN NINH', 'NOPASS', 3, 'VÃI LÚA'),
(4, 'NGUOIMUA', '444', 'XÓM 2 - XUÂN DỤC - XUÂN NINH', 'NOPASS', 4, 'VÃI LÚA'),
(5, 'SHIPPER', '555', 'XÓM 2 - XUÂN DỤC - XUÂN NINH', 'NOPASS', 5, 'VÃI LÚA');

INSERT INTO `TRIETKHAU` (`MATK`,`NGAY`,`GIATRI`) VALUES
(1, '2018-01-01',0.5);

INSERT INTO `SANPHAM` (`MASP`, `MACODE`, `TENSP`, `TRANGWEB`, `GIAWEB`,`KHOILUONG`,`GHICHU`) VALUES
(1, 'E00', 'DIENTHOAI', 'HTTP', 123,0,'SAN PHAM NAY RAT TUYET VOI'),
(2, 'E01', 'DEP', 'HTTPS', 123,0,'SAN PHAM NAY RAT TUYET VOIT'),
(3, 'E02', 'DAY', 'HTTPSS', 123,0,'SAN PHAM NAY RAT TUYET VOIG');

INSERT INTO `DONHANG` (`MADH`, `NGAY`, `TIENYEN`, `TIGIA`, `TRANGTHAI`, `GHICHU`, `MAKH`) VALUES
(1, '2018-01-01', '12', '12', 5, 'KHÔNG CÓ GHI CHÚ J', 4);

INSERT INTO `CHITIETDH` (`MADH`, `MASP`, `SOLUONG`,`MACHECK`,`MAKH`) VALUES
(1, 1, 2, 4, 2),
(1, 2, 44, 4, 2);

INSERT INTO `HOADON` (`MAHD`, `NGAYGIAO`, `MAKH`, `TRANGTHAI`, `DATCOC`,`MACHECK`) VALUES
(1, '2018-01-10', 2, 0, '12', 5);

INSERT INTO `CHITIETHD` (`MAHD`, `MASP`, `SOLUONG`, `NGAYDAT`, `TRANGTHAI`,`MACHECK`,`MADH`) VALUES
(1, 1, 2, '2018-01-02', 5, 5,1),
(1, 2, 4, '2018-01-05', 5, 5,1);